### ISSUE TITLE
Add general macro 'PREFIX = VA-' into css-lnls product

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/org.csstudio.product#1]

**Comment by gciotto** [comment]
This macro setting can be added by editing `features/org.csstudio.product.configuration.feature/rootfiles/configuration/plugin_initialization.ini`. If you need to add new macros, append the string`|new_macro,"new_value"` to the line `org.csstudio.opibuilder/macros=PREFIX,"VA-"`.
Branches `master`, `4.4.x` and `4.3.x` updated.
Commit references 1f30b9ebddc0075278f917ad2cb659844d6ff288 (master),  e0682fc5e00bddbfd0c2fa4dcd4105e82f2f9b0c (4.4.x) and 47e541e809007f3abf7845d4c9b28f89cad0e25a (4.3.x)
