### ISSUE TITLE
Add paths to common/font.def and common/color.def

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/org.csstudio.product#2]
add these two paths under Preferences/CSS Applications/Display/BOY...

For this we may have to define a standard path in the filesystem where the HLA repo is supposed to be cloned. If this is the case, I recommend /sirius/hla/css/common under linux systems.

**Comment by gciotto** [comment]
Another alternative is to define a central node in the network to put those files. In this way, the user would not have to clone any other repo.
The files would be pointed then by the addresses `http://address/css/font.def` and `http://address/css/color.def`. I've already tested this solution with my computer and it seems to work well. What do you prefer?

**Comment by xresende** [comment]
This is interesting... How you configure the node? You use an Apache server?

**Comment by gciotto** [comment]
Yes, I'm currently using a simple Apache HTTP server. The `.def` files are placed in a directory which the server has rights to access. In Ubuntu, this directory is `/var/www/html/`;

**Comment by xresende** [comment]
let's try. I put the files in '/var/www/html/cs-studio-common' at 10.0.7.55 (where other EPICS support applications are already running). Apache is already running at this node. This static IP will eventually change in the near future... 

can css-lnls be recompiled to point to the node's font.def and color.def ?

**Comment by gciotto** [comment]
I've applied the changes to the branches `master` (d0f631144d7ab1720af99327d8bdb83aea90b7ca), `4.4.x` (ab9ea184032dc3cddb9936b53669cdfa838ed159) and `4.3.x` (f46a5e8a77dcb16f6f8da9aaf8a3baae9e10cdbe). The product can be recompiled or if you prefer, you may replace the lines 
```
org.csstudio.opibuilder/color_file=...
org.csstudio.opibuilder/font_file=...
```
with 
```
org.csstudio.opibuilder/color_file=http://10.0.7.55/cs-studio-common/color.def
org.csstudio.opibuilder/font_file=http://10.0.7.55/cs-studio-common/font.def
```
in  `configuration/plugin_customization.ini` of your current product.
