### ISSUE TITLE
LNLS splash screen changed at commit d0f6311 for 4.4.x branch ?

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/org.csstudio.product#3]
There is no LNLS logo anymore. Is this intentional?

**Comment by gciotto** [comment]
If I'm not mistaken, commit d0f631144d7ab1720af99327d8bdb83aea90b7ca corresponds to the `master` branch.  I must have forgotten to update the splash screen for this branch. I'm going to apply this change. Thanks!
