### ISSUE TITLE
Generate releases to avoid having to compile CSS everytime

### ISSUE THREAD

**Issue by lerwys** [lnls-sirius/org.csstudio.product#4]
Currently, in order to use the LNLS CS-Studio we need to manually compile the source code. But this is cumbersome and can lead to subtle differences across the LNLS CS-Studio deployments.

I think it would be nice to have somewhere we could download a "ready to use" CS Studio so we can be sure what version we are referring to and to minimize differences among CS Studio users.

As an example, we could have something like this: https://ics-web.sns.ornl.gov/css/products.html

**Comment by gciotto** [comment]
I think it's a good idea! Maybe we can use the Apache HTTP Server which is already set in `10.0.7.55`. The products could be stored there too. What do you think?

**Comment by lerwys** [comment]
I think it would be better to use a public URL accessible outside LNLS. Also, this single machine (10.0.7.55) is already hosting lots of "mission-critical" services that should be hosted somewhere else.

Maybe we could talk to the IT or the Beamline Software Group (SOL) department to set this up? SOL is already hosting the Sirius wiki. So, this should be relatively easy, I guess.

**Comment by gciotto** [comment]
That works for me!  In the control group, we're facing the same problem: a common PC is hosting the archiver and alarm server. Perhaps it's more appropriate to contact the IT group directly. Do you know who handles this sort of subjects there?

**Comment by xresende** [comment]
A related matter: if you are to contact IT/SOL for servers with fixed IPs and defined names, I would recommend, if possible, to ask for the following standardized names:

sirius-ns.lnls.br
sirius-ccdb.lnls.br
sirius-archiver.lnls.br
sirius-web.lnls.br ('web' for a HTTP server ?)

Ideally we would also rename wiki-sirius.lnls.br to sirius-wiki.lnls.br, or create an alias for it...

Also, the idea of running these services as virtual machines or docker containers seems interesting...

**Comment by gciotto** [comment]
I forgot to mention that I opened a request for VM in sslinhas on March 6,. I'm currently waiting and as soon as it gets ready, I let you know!

**Comment by gciotto** [comment]
I've written a small web page with references for the CSS releases. It can be temporarily accessed at http://10.0.6.37/css-releases/products.html. After the VM is created, I'm going to move everything into it. As you can see, versions `4.5.1`, `4.4.2` and `4.3.5` are provided. Any suggestions?

**Comment by lerwys** [comment]
It seems great! I'll give it a try this week and if any suggestions come up I'll let you know!
Thanks for setting this up!

**Comment by xresende** [comment]
@gciotto , i will try to try the release tomorrow (today) and i'll let you know how it goes...

**Comment by xresende** [comment]
I am currently running the latest release from http://10.0.6.37/css-releases/products.html  and it seems stable. thanks, @gciotto.

**Comment by gciotto** [comment]
Releases can be downloaded from [here](http://csscon.lnls.br). I added some releases based on Eclipse Neon as well, in order to solve that problem of scaled screens (if you use a scale factor of 2x, for example, the icons still stayed in their original size). Concerning the domain name, I was advised that, for security reasons, it would be better to host different services (even configuration files) in different machines. In this way, the provided machine can only host our releases.
