### ISSUE TITLE
The splash screen in v4.4.x seems to change its color pallete while the application is loading...

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/org.csstudio.product#5]
is this intentional?

**Comment by gciotto** [comment]
Actually, it is not... After some research, I found out that the bitmap should be saved in 24-bit format (8R, 8G, 8B), according to [this](https://wiki.eclipse.org/Platform-releng/Updating_Branding#Splash_screen). I'm going to change it.

**Comment by gciotto** [comment]
Commits f4ec312161824df07915cce9a6476ca4168a191f, 3fa0abcbf0889bdbd7904f57750b1f4e4db3abbd and 6fe2018279bfcf011f6d647f1a38271c6d630051 fix the issue
